name: fluttergeo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  path_provider: ^2.0.11
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/cfg/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/font/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/font/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/font/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/font/poppins/Poppins-ExtraBold.otf
          weight: 800